### ISSUE TITLE
Add support for older Index Embossers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brailleapps/brailleutils#27]
```
- 3.7
- Advanced
- Basic Blue Bar
- Classic
- Domino
- Everest-S V1
- Everest-D V1
```

Original issue reported on code.google.com by `bertfrees` on 9 Mar 2011 at 10:35

**Comment by joeha480** [comment]
If there is a need for any of the above, please file an issue here: https://github.com/brailleapps/braille-utils.impl/issues
