### ISSUE TITLE
Context class loader & OpenOffice.org

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brailleapps/brailleutils#31]
```
"XxxCatalog" classes use the context class loader, which causes a problem when 
using BrailleUtils within OpenOffice.org: see also bug report at 
http://openoffice.org/bugzilla/show_bug.cgi?id=93740
```

Original issue reported on code.google.com by `bertfrees` on 10 Mar 2011 at 6:07

**Comment by joeha480** [comment]
I don't think this is relevant anymore, do you @bertfrees?

**Comment by bertfrees** [comment]
Wow this is old. I vaguely remember the issue but I think I had a workaround. Would be nice if I could find that bug 93740 I referenced.

**Comment by bertfrees** [comment]
Found it: https://bz.apache.org/ooo/show_bug.cgi?id=93740

**Comment by bertfrees** [comment]
I guess this is/was a problem in OpenOffice, nothing much BrailleUtils can do about.

**Comment by joeha480** [comment]
I am closing this then.
