### ISSUE TITLE
Add support for newer Braillo embossers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brailleapps/brailleutils#54]
```
Add support for newer Braillo embossers (300/600/650)
```

Original issue reported on code.google.com by `joel.hak...@mtm.se` on 16 Jan 2015 at 10:31

**Comment by dkager** [comment]
What needs to be done here? Dedicon uses 650SF. I'd like to add the NL (031.01) table at least, but if these machines need anything else w.r.t. volumes or page size I might as well do that too.
CC @bertfrees

**Comment by joeha480** [comment]
There hasn't been any progress in testing in two years. A release has been made with these changes. I'll just have to assume that it works. If this is not the case, open a new issue here https://github.com/brailleapps/braille-utils.impl/issues

**Comment by bertfrees** [comment]
Not two years. There is some more info here: https://github.com/snaekobbi/pipeline-mod-dedicon/issues/5.

**Comment by dkager** [comment]
We started doing test runs again in August. One result was that Java apparently converts all non-ASCII (0x0..0x127) characters to question marks. So @PaulRambags had to put in some extra magic.

**Comment by PaulRambags** [comment]
It turned out that the IBM00858 encoding (CharSet) worked fine, so in the end no "magic" was needed. If you use encodings IBM850 or windows-1252 for the conversion to ASCII, all characters above 0xFF are translated to a '?'.
